http:
  port: 9200
path:
  data: /bitnami/elasticsearch/data
transport:
  tcp:
    port: 9300
network:
  host: 172.18.0.2
  publish_host: 172.18.0.2
  bind_host: 0.0.0.0
cluster:
  name: elasticsearch-cluster
node:
  name: db2261b943cc
  master: true
  data: true
  ingest: false
